config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  #resources :users
  get 'events/new'
  get 'static_pages/home'
  get '/list', to: 'static_pages#list'
  get '/signup', to: 'users#new'
  #get '/events', to: 'events#show_members'
#  root 'events#new'
  root 'static_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :events
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
     enum course: { "理系": 0, "文系": 1 }
     
     scope :get_by_course, ->(course) {
           where(course: course)
     }
     
     has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
     has_many :followers, through: :passive_relationships, source: :follower
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "Event"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    enum course: { "理系": 0, "文系": 1, "coins": 2 }
  
    has_secure_password
    has_many :events#, dependent: :destroy
    has_many :active_relationships, class_name:  "Relationship",
              foreign_key: "follower_id",
              dependent:   :destroy
    has_many :following, through: :active_relationships, source: :followed
    
  # イベントをフォローする
  def follow(event)
    active_relationships.create(followed_id: event.id)
  end

  # イベントをフォロー解除する
  def unfollow(event)
    active_relationships.find_by(followed_id: event.id).destroy
  end

  # 現在のイベントをフォローしてたらtrueを返す
  def following?(event)
    following.include?(event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit]
  
  def index 
    #@events = Event.all
    #if params[:course].present?
      #@events = @events.get_by_course params[:course]
      #@events = Event.find(params[:course])
    #end
  end
  
  def new

  end
  
  def show

  end
  
  def show_members
  end
  
  def edit
  end
  
  private
  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    #event = User.find(params[:followed_id])
    event = Event.find(params[:followed_id])
    current_user.follow(event)
    flash[:success] = 'イベントへの参加を承りました.'
    redirect_to event
    #redirect_to show
  end

  def destroy
    event = Relationship.find(params[:id]).followed
    current_user.unfollow(event)
    flash[:success] = 'イベントへの参加を取り消しました.'
    redirect_to event
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
     user = User.find_by(student_id: params[:session][:student_id])
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      #flash[:notice] = 'ログインできた'
      log_in user
      redirect_to root_path
      flash.now[:notice] = 'In'
    else
      # エラーメッセージを作成する
      flash.now[:danger] = 'Invalid Stundet id / Password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
      @events = Event.all

      if params[:course].present?
        @events = @events.get_by_course params[:course]
        #w@events = Event.find(params[:course])
      end

  end

  def list
    @datas = Event.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy,
                                  :following, :followers]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :course, :student_id, :student, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
      # 渡されたユーザーでログインする
    def log_in(user)
        session[:user_id] = user.id
    end
    
    # 現在ログイン中のユーザーを返す (いる場合)
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    #  ユーザーがログインしていればtrue、その他ならfalseを返す
    def logged_in?
        !current_user.nil?
    end
    # 現在のユーザーをログアウトする
    def log_out
        session.delete(:user_id)
        @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_follow.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @event.id %> </div>
  <%= f.submit "参加", class: "btn btn-primary" %> 
<% end %>

  </div>
</div>

app/views/events/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following?(@event) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>

app/views/events/_unfollow.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for(current_user.active_relationships.find_by(followed_id: @event.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "取り消し", class: "btn", data: { confirm: "本当に参加を取り消してもよろしいですか?",
                                                  commit: "取り消す",
                                                  cancel:"やっぱりやめる"},
                                                  title: "確認"%>
<% end %>

  </div>
</div>

app/views/events/edit.html.erb
<p>参加人数：<%= @event.followers.count %>人</p>
    
<div class="panel-body">
  <table class="table table-bordered">
    <thead bgcolor="#90ee90">
      <tr>
	<th>名前</th>
	<th>所属</th>
	<th>学生</th>
      </tr>
    </thead>
    <tbody>
      <% @event.followers.each do |u| %>
      <tr>
        <td><%= u.name %></td>
	<td><%= u.course %></td>
	<% if (u.student == true) %>
	<td> o </td>
	<% else %>
	<td> x </td>
	<% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  
 <%= link_to "戻る", event_path(@event) %>
 
 
  
</div>

app/views/events/index.html.erb
<p>参加人数：<%= @event.followers.count %>人</p>
    
    <div class="panel-body">
        <table class="table">
              <% @event.followers.each do |u| %>
              <tr>
		      <td>
                  <li><%= u.name %></li> 
		      </td>
              </tr>
              <% end %>
        </table>
	</div>

app/views/events/new.html.erb
<h1>イベントリスト</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<html>
    <head>
        <title> イベント詳細 </title>
    </head>
    
    <body>
      <h1><%= @event.name %></h1>

      <table class="table table-bordered">
	<tbody>
	  <tr>
            <th bgcolor="#90ee90">場所</th>
	    <th><%= @event.place %></th>
	  </tr>
	  <tr>
            <th bgcolor="#90ee90">日付</th>
            <th><%= @event.begin_time.month%>月<%= @event.begin_time.day %>日</th>
	  </tr>
	  <tr>
	      <th bgcolor="#90ee90">時間</th>
	      <th><%= @event.begin_time.to_s(:time) %>〜<%= @event.end_time.to_s(:time) %></th>
	      </tr>
	  <tr>
	      <th bgcolor="#90ee90">分類</th>
	      <th><%= @event.course %></th>
	      </tr>
	   <tr>
	      <th bgcolor="#90ee90">受付状況</th>
	      <th>
	          <% if @event.begin_time > Time.now  %>
	              受付中
	          <% else %>
	              終了
	          <% end %>
	      </th>
	      </tr>
	    <tr>
	      <th bgcolor="#90ee90">料金</th>
	      <th><%= @event.fee %>円
	      </th>
	    </tr>
	    <tr height="200">
	      <th bgcolor="#90ee90">説明</th>
	      <th><%= @event.explain %>
	      </th>
	    </tr>
	      
	</tbody>
    </table>
    
    <p><%= link_to "参加者一覧", edit_event_path(@event) %></p>
      
    <div class="col-md-8">  
        <%= render 'follow_form'%>
    </div>
    </body>
</html>

app/views/events/show_members.html.erb
<p>参加人数：<%= @event.followers.count %>人</p>
    
    <div class="panel-body">
        <table class="table">
              <% @event.followers.each do |u| %>
              <tr>
		      <td>
                  <li><%= u.name %></li> 
		      </td>
              </tr>
              <% end %>
        </table>
	</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul>
          <% if logged_in? %>
            <div class=name><%= link_to "ようこそ　#{current_user.name} さん"%></div>
          <% end %>
          <div class="menu"><%= link_to "Home",  root_path %></div>
          <% if logged_in? %>
          <div class="menu"><%= link_to "My page",  current_user %></div>
          
            <div class="menu"><%= link_to "Log out", logout_path, method: :delete %></div>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    
    <title>NomikaiApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Log in") %>
<% if logged_in? %>
<% @user ||= current_user %>
<html>
  <head>
    <title> 飲み会 </title>

  </head>

  <body>
    <div class="center jumbotron">
      <h1><font face="cursive">リク飲み for ITF</font></h1>
      <nav>
        <% if false %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "イベント一覧",events_path%></li>
          <li><%= link_to "ユーザ一覧",users_path%></li>
        </ul>
        <% end %>
      </nav>

    </div>

    <div class="text-right">
    <div class="btn-group" role="group"> 
      <%= form_tag(root_path, method: "get") do %>
      <%= label_tag :course, "絞り込み" %>
      <%= select_tag :course, options_for_select(Event.courses), include_blank: true %>
      <%= submit_tag "検索" %>
      <% end %>
    </div>
    </div>

    <div class="panel panel-success">
      
      <div class="panel-heading">
	<h5 class="panel-title">イベント一覧</h5>
      </div>
      
      <div class="panel-body">
	
        <table class="table-bordered">
	  
	  <tbody>
	    
	      <div class="row">
		<% @events.each do |event| %>
		
                <font size="5"><div class="col-sm-6">
		    <div class="box8"><%= link_to event.name,event_path(event.id)%></font>
		<% if (event.course == "理系") %>
		<br><span class="label label-danger"><%= event.course %></span></br>
		<% else %>
		<br><span class="label label-info"><%= event.course %></span></br><% end %>
		<%= event.begin_time.month %>月<%= event.begin_time.day %>日
                <% if @user.following?(event) %><br><span class="label label-success">参加中</span></br>
		<% else %><br></br><% end %>
		</div>
		</div>
	      
	      
	      <% end %>
	      
	    </div>
	  </tbody>
        </table>
      </div>
      
    </div>
    
  </body>
</html>
<% else %>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>統一認証システム (Unified Authentication System)</title>
  </head>
  <body>
<img src="https://idp.account.tsukuba.ac.jp/idp/images/ia-logo.gif" />
<h2>リク飲み　</h2>
<h2>統一認証システム (Unified Authentication System)</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>
    <br>
      <%= f.label :student_id, "Stundet id" %>
      <%= f.number_field :student_id %>
      <td>
      (<a target="_blank" href="http://www.cc.tsukuba.ac.jp/wp/service/account/#utid-13">UTID-13</a> 
      or <a target="_blank" href="http://www.cc.tsukuba.ac.jp/wp/service/account/#utid-name">UTID-NAME</a>)</td>
    </br>
    <br>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </br> 
      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
    </div>
    <div class="col-md-6 ">
    <div class="text-left">

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
    <br>
    
      <ul>
      <li align = "left">このページをブックマークしないでください．</li>
        <li style="list-style-type: none">
          (Please do not bookmark this page.)
        </li>
        <li style="list-style-type: none">
          <span style="font-size: x-small">
            このページに移行する前の，システムごとのURLをブックマークするようにしてください．
          </span>
        </li>
        <li style="list-style-type: none">
          <span style="font-size: x-small">
          (Please bookmark system-specific URL before jumping to this page.)
          </span>
        </li>
      </ul>
    </div>
    </div>
</div>

  </body>
</head>

<% end %>

app/views/static_pages/list.html.erb
<h1>イベントリスト</h1>
<p>Find me in app/views/events/new.html.erb</p>
<table>
    <% @datas.each do |data| %>
    <tr>
        <td>
        <%= data.name %>
        </td>
    </tr>
    <% end %>
</table>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :course %>
    <br>
    <%= select_tag :course, options_for_select(User.courses), include_blank: true %>
  </div>
  
  <div class="field">
    <%= f.label :student_id, "Student id" %>
    <br>
    <%= f.number_field :student_id %>
  </div>


  <div class="field">
    <%= f.label :student %>
    <br>
    <%= f.check_box :student %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Cource</th>
      <th>Student</th>
      <th>Student id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.course %></td>
        <td><%= user.student %></td>
        <td><%= user.student_id %></td>
        <td class="show_edit"><%= link_to 'Show', user %></td>
        <td show_edit><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>



<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<div class="namea"><%= @user.name %></div>
<div class="nameb">さんのユーザー情報</div>

<table border="1" class="mytable">
  <tr>
  <th scope="row"><strong>Email:</strong></th>
  <td><%= @user.email %></td>
  </tr>

  <tr>
   <th scope="row"><strong>Course:</strong></th>
   <td><%= @user.course %></td>
  </tr>

  <tr>
    <th scope="row"><strong>学籍番号:</strong></th>
    <td><%= @user.student_id %></td>
  </tr>

  <tr>
    <th scope="row"><strong>区分:</strong></th>
    <% if  @user.student %>
    <td>学生</td>
    <% else %>
    <td>卒業生</td>
    <% end %>
  </tr>  
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
     <%= link_to 'Back', users_path %>
<br></br>
     <%= image_tag("beer.jpg") %>